# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QButtonGroup, QFileDialog
import sys
from PIL import Image
from PyQt5 import uic


def add(file, color):
    img = Image.open(file)
    x, y = img.size
    size = (x, y)

    x1, y1 = (int(x * 1.03), int(y * 1.03))
    new_size = (x1, y1)
    new_im = Image.new("RGB", new_size, (255, 255, 255))
    new_im.paste(img, (int((new_size[0] - size[0]) / 2),
                       int((new_size[1] - size[1]) / 2)))
    img1 = new_im
    x, y = img1.size
    size = (x, y)

    x1, y1 = (int(x * 1.06), int(y * 1.06))
    new_size = (x1, y1)
    new_im = Image.new("RGB", new_size, color)
    new_im.paste(img1, (int((new_size[0] - size[0]) / 2),
                        int((new_size[1] - size[1]) / 2)))
    name = file.split('.')
    format = name[-1]
    new_name = ''.join(name[:-1]) + '_bordered.' + format

    new_im.save(new_name)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")

        Form.resize(746, 654)
        path = 'untitled.ui'
        uic.loadUi(path, self)
        self.fname = None

        self.pushButton.clicked.connect(self.get_image)
        self.pushButton_2.clicked.connect(self.add_border)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def get_image(self):
        self.fname = QFileDialog.getOpenFileName(self, 'Выбрать картинку', '')[0]
        name = self.fname.split('/')[-1]
        self.label.setText(f'Файл "{name}" загружен!')

    def add_border(self):
        try:
            if self.radioButton.isChecked():
                color = (107, 142, 35)
            elif self.radioButton_2.isChecked():
                color = (30, 144, 255)
            else:
                color = (255, 127, 80)
            add_borders.add(self.fname, color)
            self.label_2.setText('Успешно')
            self.label.setText('')
        except Exception as E:
            print(E)
            self.label_2.setText('Ошибка!')


class MyWidget(QMainWindow, Ui_Form):
    def __init__(self):
        super().__init__()
        # Вызываем метод для загрузки интерфейса из класса Ui_MainWindow,
        # остальное без изменений
        self.setupUi(self)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.setWindowTitle('Borders')
    ex.show()
    sys.exit(app.exec_())
